services:
  mariadb:
    image: 'mariadb:11.4'
    container_name: 'goldmanager-e2e-mariadb'
    environment:
      - 'MYSQL_DATABASE=goldmanager'
      - 'MARIADB_PASSWORD=mypass'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
      - 'MARIADB_USER=myuser'
      - 'MYSQL_ROOT_HOST=%'
    ports:
      - '3317:3306'
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 5m
      interval: 10s
      timeout: 5s
      retries: 60
    labels:
      org.springframework.boot.readiness-check.tcp.disable: true
