name: E2E Playwright

on:
  pull_request:

jobs:
  e2e:
    name: Run Playwright E2E
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:11.4
        env:
          MYSQL_DATABASE: goldmanager
          MARIADB_USER: myuser
          MARIADB_PASSWORD: mypass
          MARIADB_ROOT_PASSWORD: verysecret
          MYSQL_ROOT_HOST: "%"
        ports:
          - 3307:3306
        options: >-
          --health-cmd="healthcheck.sh --connect --innodb_initialized"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            e2e/package-lock.json
            frontend/package-lock.json

      - name: Install E2E dependencies
        working-directory: e2e
        run: npm ci

      - name: Install Playwright system deps and browsers
        working-directory: e2e
        run: npx -y @playwright/test@1.54.2 install --with-deps

      - name: Run Playwright tests
        working-directory: e2e
        env:
          E2E_DB_HOST: 127.0.0.1
          E2E_DB_PORT: "3307"
          E2E_DB_WAIT_MS: "360000"
          E2E_HEALTH_TIMEOUT_MS: "600000"
          E2E_WEBSERVER_TIMEOUT_MS: "720000"
        run: npm test

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-html-report
          path: e2e/test-results-html
          if-no-files-found: ignore

      - name: Upload quick status JSON
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-last-run
          path: e2e/test-results/.last-run.json
          if-no-files-found: ignore
